config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

root 'pages#homepage'

get 'about', to: 'pages#about'

resources :users
resources :posts do
    resources :comments
    resources :bookings
  end  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord

    belongs_to :user    

    enum status: [:pending, :paid, :cancelled]

    after_create :generate_ref_no

    def generate_ref_no
        #y7w40p
        random_string = SecureRandom.hex(3)
        self.ref_no = random_string
        self.save
      end
    
      def calculate_total
        total_days = days_between + 1
        self.total = booking.price_per_day * total_days
        self.save
      end
end   

app/models/comment.rb
class Comment < ApplicationRecord
 belongs_to :user
 belongs_to :post
end    

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :user

  validates :caption,presence: true 

  has_one_attached :photo

  has_many :comments, dependent: :destroy

  has_many :bookings
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_one_attached :avatar
  
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_many :bookings



  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

    def create
        @post = Post.find(params[:post_id])
        @booking = @post.bookings.create(user_id: current_user.id, post_id: @post, total: @post.price_per_day)

        if @booking.save
            redirect_to post_booking_path(@post, @booking), notice: 'Booking was successfully created.'
        else
            redirect_to post_path(@post), alert: 'There was an error. Please try again.'  
        end      
    end     

    def show
        @booking = Booking.find(params[:id])
    end    
end  

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        @post = Post.find(params[:post_id])
        @comment = @post.comments.create(comment_params.merge(user_id: current_user.id))
    
        if @comment.save 
            redirect_to post_path(@post), notice: 'Comment was successfully created'
        else 
            redirect_to post_path(@post), notice: 'There was an error'            
    end   
end  

    private
        def comment_params
            params.require(:comment).permit(:content)
        end
    end        

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!

  def homepage
    @welcome ="Hobbook"
    @posts = Post.all
  end

  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def create
    post = current_user.posts.create(post_params)

    if post.save
      redirect_to user_path(current_user), notice: "Your post was successfully created."
    else
      redirect_to user_path(current_user), notice: "There was an error."
  end
end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments
    @booking = Booking.new
  end 

  def edit
    @post = Post.find(params[:id])
  end  

  def update
    @post = Post.find(params[:id])
    @post.update(post_params)

    if @post.save
      redirect_to post_path(@post), notice: 'Post was succesfully updated'
    else 
      render :edit 
  end  
end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to user_path(current_user), notice: 'Post was successfully deleted'
  end 



  private
    def post_params
      params.require(:post).permit(:caption, :photo)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @post = Post.new
    @posts = @user.posts
    @bookings = @user.bookings
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)

  if @user.save
    redirect_to user_path(@user), notice: 'Your profile was successfully updated'
  else
    render :edit
  end
end

  private
    def user_params
      params.require(:user).permit(:username, :birth_date, :avatar)
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/show.html.erb
<br/>
<section class="single-booking-page">
<div class="card" style="width: 600px; margin-left: 35%;">
<div class="booking-details">
    <div class="card-body">
        <h4 class="card-title" style="margin-left: 35%;">Booking details</h4>
    </div>
    <ul class="list-group list-group-flush">
        <li class="list-group-item">Reference No: <%= @booking.ref_no %></li>
        <li class="list-group-item">Total: <%= @booking.total %></li>
        <li class="list-group-item">Status: <%= @booking.status %></li>
    </ul>

    <% if @booking.status == 'pending' %>
        <div class='booking-payment' style="margin-left: 40%;">
            <%= form_with url: '/stripes', method: :post do |f| %>
            <%= f.text_field :booking_id, value: "#{@booking.id}", hidden: true %>
            <%= f.submit 'Confirm Booking'%>
        <% end %>
        <br/>
        </div>
    <% elsif @booking.status == 'cancelled' %>
        <p>This Booking has been cancelled.</p>
    <% else %>
        <button>
            <%= link_to 'View payment details', listing_booking_payment_details_path(@booking)%>
        </button>
    <% end %>
</div>    
</div>   
</section> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hobbook2021</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbo-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbo-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbo-track': 'reload' %>
    
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCP8FHRDzBFXQhRnQCoeFojoUz2L4fsSUs&callback=initMap"></script>
  </head>

  <body>
  
    <%= render 'shared/header' %>
    <%= render 'shared/flash_message' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<%= turbo_frame_tag 'test' do %>
  
<% end %>

app/views/pages/homepage.html.erb
<%= turbo_frame_tag 'test' do %>
  <h1 style='color: #0d6efd; font-weight: bold; margin-left: 45%;'> <%= @welcome %> </h1>
<% end %>

<div class="card" style="width: 600px; margin-left: 35%; border-radius:15px;">
<% @posts.each do |post| %>
  <%= link_to post_path(post) do %>
  <% if post.photo.attached? %>
    <%= image_tag post.photo, style: 'width: 600px; border-radius: 15px;' %>
  <% end %>
  
  <div class="card-body">
    <h5 class="card-title btn btn-primary" style="height: 5px;  padding: 10px 10px 30px 10px; margin-left: 38%;"> <%= post.caption %></h5>
  </div>  
  <% end %>
  <hr></hr>
<% end %>
</div>

app/views/posts/edit.html.erb
<br/>
<section class="single-post-edit">
    <div class="card" style="width: 600px; margin-left: 35%; height: 150px;">
    <div class="card-body">
        <h4 class="card-title" style="margin-left: 35%;">Booking details</h4>
    </div>
 <%= form_for @post do |f| %>  
  <%= f.file_field :photo, style:'padding-left: 5px; padding-bottom: 20px;' %>
  <%= f.label :caption %>
  <%= f.text_field :caption %>
  <%= f.submit 'Post' %>
 <% end %> 
 
 </div>
</section>



 

app/views/posts/show.html.erb
<div class="card single-post-show" style="width: 600px; height: 1000px; margin-left: 35%; border-radius:15px;">

  <% if @post.photo.attached? %>
    <%= image_tag @post.photo, style: 'width: 600px; border-radius: 15px;' %>
  <% end %>
    
    <h5 class="card-title" style="margin-left: 215px;"> <%= @post.caption %></h5>
    

    <div class="comment-form">
        <%= form_with(model: [@post, @comment]) do |f| %>
            <%= f.text_field :content, placeholder: 'Write your comment here', style:'width: 84.5%; border-radius: 5px;' %>
            <%= f.submit 'Comment' %>
        <% end %>    
    </div>    
    <br/>
    <div class="post-comments">
        <% @comments.each do |comment| %>
            <p class="nama" style="color: white; background-color: #0d6efd; border-radius: 5px; padding-left: 5px; " ><%= comment.user.username %></p> 
            <p class="nama" style=" border-radius: 5px; padding-left: 5px; border-bottom: 1px solid black;">  comment: <%= comment.content %> </p>
         <% end %>   
     </div>    
     <br/> 
     <div class="bookings">
        <%= form_with(model: [@post, @booking], data: {turbo: false}) do |f| %>  
          <%= f.submit 'Book', 
          style:'margin-left: 40%; 
                 color: white; 
                 background-color: #3DE9D8; 
                 border: none; 
                 width:70px; 
                 height: 35px; border-radius: 5px;' %>
        <% end %>  
     </div>

</div>

app/views/shared/_flash_message.html.erb
<section class="flash-message">
  <% flash.each do |key,value| %>
    <%= value %>
  <% end %>
</section>

app/views/shared/_header.html.erb
<ul class="nav justify-content-center navbar-dark bg-primary" style="height: 50px; font-size: 20px; ">
  <li class="nav-item">
    <a class="nav-link active" style="color: white; aria-current="page" href=<%= root_path %> >Hobbook</a>
  </li>
  <% if user_signed_in? %>
  <li class="nav-item">
    <a class="nav-link" style="color: white;" href= <%=user_path(current_user)%> >Profile</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" style="color: white;" href= <%= edit_user_path(current_user)%> >Setting</a>
  </li>
  <li class="nav-item" style="padding-top: 5px;">
    <%= button_to 'Logout', destroy_user_session_path, method: :delete, data: { confirm: 'Are you sure?'}, style: 'background-color: #F43122; border: none; color: white; height:30px; border-radius: 5px; padding-bottm: 15px; margin-top: 5px;'  %>
  </li>
  <% else %>
    <li class="nav-item">
    <a class="nav-link" style="color: white;" href= <%= new_user_registration_path %> >Sign Up</a>
  </li>
      <li class="nav-item">
    <a class="nav-link" style="color: white;" href= <%= new_user_session_path %> >Login</a>
    <% end %>
  </li>
</ul>

app/views/users/edit.html.erb
<div class="card" style="width: 18rem; width: 1000px; height: 300px; margin-left: 25%;">
<section class="user-setting">
  <div class="card-body">
  <h5 class="card-title" style="font-size: 30px; margin-left: 35%; padding-bottom: 15px;">Profile Settings</h5>
  <div class="set" style="margin-left: 5%;">
  <%= form_with(model: @user) do |f| %>
    <%= f.file_field :avatar %>
    <%= f.label :username %>
    <%= f.text_field :username %>
    <%= f.label :birth_date %>
    <%= f.date_field :birth_date %>
  <%= f.submit 'Save' %>
  <% end %>
  </div>
  </div>
</section>
</div>

app/views/users/show.html.erb
<section class="user-profile">
<div class="card" style="width: 45%; margin-left: 30%;">
  <div class="card-body">
  <h1 class="card-title" style="padding-left: 110px; font-size: 25px; margin-left: 32%; color: #0d6efd;"> <%= @user.username %> </h1>
    <div class="user-avatar" style="padding-left: 10px;">
      <% if @user.avatar.attached? %>
        <%= image_tag @user.avatar, style: 'width:200px; border-radius: 15px; margin-left: 35%;' %>
      <% end %>  
    </div>
  </div>
  <div class="user-details">
    <p style="margin-left: 15%; border-bottom: grey solid 1px; border-left: 1px solid black;">Username: <%= @user.username %></p>
    <p style="margin-left: 15%; border-bottom: grey solid 1px; border-left: 1px solid black;">Birth: <%= @user.birth_date %></p>
  </div>
  <hr></hr>

  <div class="upload" style="margin-left: 15%;">
  <% if current_user == @user %>
    <%= form_for @post do |f| %>
      <%= f.file_field :photo, style:"  border: black solid 1px; height:30px; border-radius: 5px; " %>
      <%= f.label :caption, style: " height:25px; border-radius: 5px; margin-left: 10px;" %>
      <%= f.text_field :caption %>
      <%= f.submit 'Post', style:" background-color: #0d6efd; border: none; color: white; height:30px; border-radius: 5px"; %>
    <% end %>
  <% end %>
  </div>
  <br/>

<% @posts.each do |post| %>
  <% if post.photo.attached? %>
    <div class="col-md-4">
    <%= image_tag post.photo, style: 'width: 600px; margin-left: 45%; border-radius: 20px;'  %>
    </div>
  <% end %>

  <div class="card-body">
    <h5 class="card-title" style="height: 1px; margin-left: 42%;"> <%= post.caption %></h5>
  </div>  
  <hr></hr>
    <div class="card-body" style="margin-left:30%;  ">
      <a href=<%= post_path(post) %> class="card-link btn btn-primary">Post</a>
        <%= link_to 'Direction', "https://maps.google.com/?q=#{@post.latitude},#{@post.longitude}", target: '_blank', style: 'color: white; background-color: #0d6efd; border-radius: 5px; text-decoration: none; font-size: 15px; padding: 7px 5px 10px 5px;' %>
        <% if current_user == @user %>  
      <a href=<%= edit_post_path(post) %> class="card-link btn btn-primary">Edit</a>
        <button type="button" class="btn btn-danger"> <%= button_to 'Delete', post_path(post), method: :delete, data: { confirm: 'Are you sure?'}, style: 'background-color: #F43122; border: none; color: white; height:30px; border-radius: 5px;' %>
    </div>
    <% end %>
  <% end %>
  </div>
</section>